global.css
Tested in Edge, please check mac.
=> #14 Adjusted image pos

ogkush.js
=> FIX #6 (dirty) add 10 ressources to lock

ogkush.js
(has already been but maybe skipped by a rollback)
=> FIX #15 Correct dock costs

ogkush.js
v8 adds alliance class so items below weren't parse
=> Fix #43 v8 spy report parsing

global.css, ogkush.js
Fix:
- Fix the case that General and Production were based in different values (json inner saved data)
Improvements:
- Remove Production from Empire (since it's now available in Statistics)
- Add fields and temperature to Production Statistics
=> General Statistics Fix & Production Statistic Improvement

manifest.json, ogkush.js
Production Statistics Fix
- Fix to get a statistic production even storage is full
Quick Dispatcher Fix
- Fix to try avoid crash when change between fleet1 and fleet2
=> Production Statistics Fix & Quick Dispatcher Fix

ogkush.js
1. remove that the mission type gets defaulted to transportation (3)
2. fix the mission type priority order
3. fix that the user choosen 'harvestMission' also gets selected when the target is one of the players planets/moons
=> fix default mission behaviour

ogkush.js
1. fixes the NaN resource bug on the fleetpage
the internal logic from fleetdispatcher needs a default mission other than 0 to calculate consumption and other values
undo's some unneeded parts of #69
=> fix needed default mission

ogkush.js
1. shorten the precision for values over 1kk
=> shorten high value precision

ogkush.js
This will avoid throwing an error
=> fix: no JSON() found when parsing combat message

ogkush.js
Modded PantrySync feature to respect the new pantry limitations and better manage sync errors
=> Mod PantrySync requests to fix sync errors

global.css, ogkush.js
Add the ability to:
- ArrowUp/ArrowDown to +1/-1 on input field
- **Shift** + ArrowUp/ArrowDown to +10/-10 on input field
- **Ctrl** + ArrowUp/ArrowDown to +100/-100 on input field
Works on all *ogl-formatInput*
=> feat: add ArrowUp and ArrowDown for numbers

global.css, ogkush.js
=> Fixes for banner styles on messages, premium and shop pages

ogkush.js
=> fix(spy): pagination check

package.json, readme.md
=> fix: let's have only one formatting command

ogkush.js
…ith reduction for LF buildings
=> mrc reduction for production buildings (both LF and normal) and megalith reduction for all LF buildings

ogkush.js
This PR adds PTRE link to top menu.
=> Add PTRE link to top menu

ogkush.js
=> Use localized thousand separators in harvest report parsing

ogkush.js
=> point&comma in flying stats/overview

ogkush.js
=> fix removeNumSeparator call in debris harvest report parsing

ogkush.js
=> Fix/planets fleet activity with ACS

ogkush.js
=> add bonus event in research time calculation

ogkush.js
=> more specific selector to search for tooltip with fleet info

ogkush.js
=> enable disableAutoFetchEmpire settings + update description text

ogkush.js
=> add a delay to combat report fetching

global.css, ogkush.js
Reverts ogame-infinity/web-extension#160
Rollback after many players can get functional playing with fleet cargo.
=> Revert "Improvement/return on investment"

ogkush.js
Please, test that works ok also in no deuterium debris expedition fields.
=> fix deuterium debris in galaxy + get rid of .html() use in checkDebris() method

ogkush.js
Update Expedition Messages: Turkish #17
=> Update Expedition Messages: Turkish #17

ogkush.js
Light fighter Mk II / Cruiser Mk II had an incorrect base value of 10'000 deut instead of 100'000. I've checked other LF techs and buildings against LFMaster903.xlsx and found no other incorrect value :)
=> fix: LF tech base cost invalid for human

ogkush.js
Hi all,
After Antigame, Ogame Infinity is perfect for me. And I committed to fix the mistakes I saw.
I would appreciate it if you approve the PR.
=> Turkish values updated.

global.css, ogkush.js
- combat and exploration statistic now work again (M & C ; D still not supported)
- improve display of DF in galaxy view
- patch the rentability highlight of DF
+ Handle the French tooltip for crawler
=> Debris Field patch and improvement

ogkush.js
bugfix: Fixes the problem of overlapping content in the details of the technologies caused by slow connections or fast actions (multiple clicks).
=> Technologies Details

.eslintrc.js, global.css, ogkush.js
=> improve storage display for big number

.eslintrc.js, ogkush.js, package-lock.json, package.json, readme.md
See https://github.com/ogame-infinity/web-extension/issues/218
=> Update prettier and eslint versions

ogkush.js
Careful with Spanish on fleet too, may be too long, please check
=> add some localization for fleet2

global.css
* Fix galaxy button to send buddy request.
* Corrected overwriting of the style of the blue buttons.
=> Style Of Buttons.

ogkush.js
* Fix case when select principal tab of messages and the option no has sub-tabs only his main container.
=> Fix message analyzer with no sub-tabs.

util/service.ptre.js
* PTRE requests that do not send the "tool" parameter have been corrected.
=> Fix PTRE query parameters in POST requests.

global.css, ogkush.js
=> Improvement/link handling with PTRE and add localization 

src/ogkush.js
fix navigationArrows in mobile broken in the last release because the changes to handle localised keyboards
=> make navigationArrows use key property + replace remaining code -> key

src/global.css
Improved contrast between active and inactive ships to be sent on expeditions.
Old.
New.
=> Expeditions Options / Improved contrast 

src/ogkush.js
fix unusable adjustBox, food is not accounted in stats anyway
=> remove unused food input in adjustBox for combat stats

src/ogkush.js, src/util/wait.js, src/util/waitFor.js
Fixes cases where the plugin crashes when it loads quickly.
New util implementation for WaitFor
=> Fix: Fast start plugin load, and WaitFor

src/ogkush.js
In order to track more PTRE target's activity, we can increase stalk list size to 20.
=> fix(stalk): Increase Stalk list size to 20

src/ogkush.js
Test fails when History is empty.
This PR fixes it.
=> fix(activities): Fix error while History is empty

src/ogkush.js
We want to send PTRE activities during player stalk.
This PR adds stalked player to History list.
=> feat(activities): Send PTRE activities during stalk

src/ogkush.js
Add PT-BR translate to OG Infinity Extension
=> Improvement: Add PT-BR translate

src/ogkush.js
disable direct probing in stalks and target list until better way implemented or GF start to wake up
=> disable direct probing in stalks and target list

src/ogkush.js
=> fix undefined production when you have a lvl 0 mine

src/ogkush.js
=> patch crash on spy table for position without coordinate in title

src/ogkush.js, src/util/json.js
Implement JSON extraction and error handling functionalities
Integrated a new function, extractJSON, to locate and extract the inaugural valid JSON object within a specified string.
Developed a custom InvalidJSONError class to throw an error when the string does not contain any valid JSON.
=> Implement JSON extraction and error handling functionalities

src/ogkush.js, src/util/time.js
- Created a new time module with a getTimeFromISOString() function that was early a private function of technoDetail() method
- Fixes overviewDates() crash with new countdown DOM structure
- Adds support to the new Mecha Shipyard to it
By the way, there is a cosmetic issue left to be addressed, in Shipyard caused with the new shipyard selector:
=> Fix/11.13.0 breaks overview dates()

src/ogkush.js
disable betterTooltip, temporary workaround until a transition in OGI from tipped to tippy is done
=> disable betterTooltip()

src/ogkush.js
=> fix the way we get energy requirement for building

src/ogkush.js
=> patch the new Id data-tooltip-title inFlightRessource/nbShipRanking

src/global.css
=> fix the color for ressources in tooltip

src/global.css
=> fix the display for mech shipyard

src/ogkush.js
=> fix harvest

src/global.css
=> clean expe message display

src/ctxcontent/services/analyzer/SpyMessagesAnalyzer.js
[ogi-chrome.zip](https://github.com/user-attachments/files/16022342/ogi-chrome.zip)
[ogi-firefox.zip](https://github.com/user-attachments/files/16022343/ogi-firefox.zip)
=> feat(ptre): owner spy

src/global.css
=> add margin to keep Planet list at fix point from the top

src/global.css
=> small change for margin in p16 PM find

src/global.css, src/ogkush.js
=> add hightlight around selection of ship/misssion for collect

src/ctxcontent/services/analyzer/ExpeditionMessagesAnalyzer.js, src/global.css
=> PM discovery - fix color/display - add amount - add size

src/ctxcontent/services/analyzer/SpyMessagesAnalyzer.js
Uncaught SyntaxError: invalid assignment left-hand side
=> fix a dataset converted as get into set

src/ctxcontent/services/analyzer/FightMessagesAnalyzer.js
=> fix the border color for each type of fight

src/ctxcontent/services/analyzer/ExpeditionMessagesAnalyzer.js
=> fix - uggly patch for alien / pirate expe

src/ctxcontent/services/analyzer/ExpeditionMessagesAnalyzer.js, src/ogkush.js, src/util/standardUnit.js
=> feat - add MSU support for both fight and expe stats

src/ctxcontent/services/analyzer/ExpeditionMessagesAnalyzer.js, src/ctxcontent/services/analyzer/FightMessagesAnalyzer.js, src/ctxcontent/services/analyzer/HarvestMessagesAnalyzer.js, src/global.css, src/ogkush.js
=> feat add msu in message fight and harvest

src/ctxcontent/services/analyzer/TradeMessagesAnalyzer.js, src/ctxpage/messages/index.js, src/ogkush.js, src/util/OGIData.js, src/util/enum/messageType.js
=> add msu +/- on trading message

src/global.css
=> change CSS to impre ressources display in transport message

src/ctxcontent/services/analyzer/FightMessagesAnalyzer.js
- fix the sum locked at 0 in case of reset 
- improve handling of duplicate combat rapport
=> fix the combat Sum on reset / for double accounting detection

src/global.css, src/util/needs.js
=> fix case when GF use myWorlds instead of myPlanets AKA no moon

src/ogkush.js
=> fix the bug for aliance tag with space trucated in search

src/global.css
=> hide new ogame v12 planet list highlight 

src/global.css
v11:
v12 (before):
v12 (after):
=> fix planet/moon icons position in planetlist with v12

src/ogkush.js
=> fix(ranking): tooltip on ranking page

src/global.css
before, non-ranking page:
before, ranking page:
after, non-ranking page:
after, ranking page:
=> Fix/v12 cosmetics resource bar & logo

src/ogkush.js
=> fix: Recycling total in General don't use LF +ship enum

src/ogkush.js
=> Lock trigger error when content has no input

src/ctxcontent/services/analyzer/ExpeditionMessagesAnalyzer.js, src/ogkush.js
=> feat(bhole): count losses on expeditions

src/ogkush.js
=> fix(planet-list): refresh

src/ogkush.js
fix negative / positive error for old manual data
=> fix Bh sum of manual + auto

src/global.css
=> increase footer width to 950px to be able to add our version number

src/ogkush.js
do a final check before send changes data on galaxy to ensure that game variables or DOM have not been modified
=> do final check before send changes data on galaxy

package-lock.json, src/ogkush.js
- add a trim on the pantry key 
- remove old lock node in the pantry
- add missing node in pantry like new lock
=> pantry - add missing node like Needs + some cleaning

src/global.css
=> Some css fixes
