ogame-infinity/web-extension

- ogkush.js
line 9695, universe was hardcoded
```js
generateIgnoreLink(playerId) {
return `https://s169-fr.ogame.gameforge.com/game/index.php?page=ignorelist&action=1&id=${playerId}`;
}
generateBuddyLink(playerId) {
return `https://s169-fr.ogame.gameforge.com/game/index.php?page=ingame&component=buddies&action=7&id=${playerId}&ajax=1`;
}
```
should be
```js
generateIgnoreLink(playerId) {
return `https://s${this.universe}-${this.gameLang}.ogame.gameforge.com/game/index.php?page=ignorelist&action=1&id=${playerId}`;
}
generateBuddyLink(playerId) {
return `https://s${this.universe}-${this.gameLang}.ogame.gameforge.com/game/index.php?page=ingame&component=buddies&action=7&id=${playerId}&ajax=1`;
}
```
> FIX Adding players to block list links to lobby (fr) #21

- ogkush.js
(Fuel already has negative value unlike Losses so subtracting it mean adding)
> Fix : Issue #22 Incorrect fuel consumption sum

- ogkush.js
Fix to solve the issue when all/none ships were clicked to fast and sequentially (that causes Infinity to break)
> Fix QuickDispatcher - Select All/None Ships

- global.css
- ogkush.js
1. fixed misaligned planet resource sum
2. fixed misaligned construction icons
Before:
After:
Also works on the small overview:
> fix planet list alignments

- global.css
1. fix the resource icons in the statistics dialog
Before:
After:
> fix stat resource icons

- global.css
Make it a bit better on pixel matching:
- the wrapper is the correct size
- the item inside are taking the entire width 
- the title is taking the entire width
> fix: sidestalker alignments

- ogkush.js
Adds some icons next to the planets to see what mission are currently running on which planet. 
This might be useful in order to quickly check if a planet is not running on expedition and... many other things :) 
Note: as of today, the number of mission displayed are limited to 8 and when more than 2, the image sizes are divided by 2
> feat(planetList): add current missions

- ogkush.js
The fleetDispatcher.updateMissions definition was always done, not only in the fleetDispatch page were the Ogame fleetDispatcher is accessible.
> Fix use of fleetDispatcher outside fleetDispatch page

- ogkush.js
Original issue:
After fix:
In response to Issue #115
> fix: Ensured successful resource parsing in espionage reports

- main.js
- ogkush.js
Hello @everteckhardt ,
I am PTRE developer and i just find out that my website was integrated to OG Infinity. And i saw some stuffs that could be improved.
OG Infinity is using same interfaces than OGLight. To improve analysis and for debug purposes, it's better to add a different `tool` name than OGLight's one to PTRE requests.
From now on, please add `?tool=infinity` GET parameter to each and every requests to PTRE `ptre.chez.gg/scripts/` route.
> [PTRE] Add (or update) tool name sent to PTRE backend

- ogkush.js
Warsaalk leaves and closed down trashsim server. Fortunately the SGO of the Dutch community will start hosting the projects. 
[https://board.en.ogame.gameforge.com/index.php?thread/835718-trashsim-and-ogotcha-shutting-down/](url)
As now is working a redirection from old server to new one, but we can expect that this will not last forever. Updating now the link we can forget about it.
> update trashsim link

- global.css
- ogkush.js
Add discoveries statistics - independant from expeditions statistics
- LF discoveries are not reported in "Object" and "Fleet" into Expedition statistics anymore
- Additional color is added to "Expedition" messages to treat these cases : Artefact found (Yellow), Discovery of Human, Discovery of Rock'tal, Discovery of Mechas, Discovery of Kaelesh (Color based on LF technologies graphics chart)
- A new tab is added in statistics to show Discoveries statistic (Exeperience and Artefacts) like Expedition statistics (only if it is an LF universe)
For the formating, "npm run format" change all the file, so i present you an hand-formatted version
I am a newbie in JS so i take all your advices ;)
> Add discoveries statistics

- ogkush.js
Regression was introduced in commit fd6d50a : for an explorer, `maxTotal` calculation changed from (probably because of a style change ?)
```
maxTotal *= 2 [pathfinder boost] * (1 + 0.5[explorerBonusIncreasedExpeditionOutcome]) * speed
```
To
```
maxTotal *= 2 [pathfinder boost] * (1 + 0.5[explorerBonusIncreasedExpeditionOutcome] * speed)
```
Which resulted in incorrect total (on speed 2, you'd get 20M max instead of the correct 30M, for example).
I took the liberty of splitting the code into separate statements for clarity purpose.
> fix: Expedition max total calculation for explorer class

- ogkush.js
Until a proper code is done in updateProductionProgress() and/or LFBonusUpdate process, disable auto LF bonus updates in moon to avoid endless needs of more updates in next pages until the update is done in the planet.
This is becase in updateProductionProgress() there is marking of needed update always until do the update in a planet and the progress mark get deleted. This is also a potential race condition, the lfupdate is async, seems to be executed later and clears the needs of more updates previously marked. **That has to be fixed to avoid potential future problems.**
> disable auto LFBonusUpdates in moons

- ogkush.js
- fixed system change in fleet 1 page with up&down arrows (works in the system input box and with nothing selected): now work correctly (without fleetDispatcher errors) with key pressed
- exclude key shorcuts in fleet page when chatbox area is the active element
- removed some duplicate shortcuts calling -> no errors with fleetDispatcher
> overhaul keyboardActions() in fleet page

- src/ogkush.js
fixes padlock ships preselection, transport ships preselection (collect, harvest) and event trashsim prefill when comma is the locale group separator
> replaces fixed point as group separator by fromFormatedNumber()

- src/global.css
- src/ogkush.js
before:
after:
- removed old now useless page fleet3 rules for resource buttons area and change the current ones to a grid rule working with new version changes
- removed the left menu displacement and help component minimization as with the new newbie system it can be hidden with native options
> Fix/v11 cosmetic issues directives & fleet2 resource buttons

- src/ogkush.js
- replaced the `setTimeout()` in `expedition()` method for calling auto expedition with `wait.delay()` and increased the delay to 250 ms
- made a general throttle function. may be interesting make a class of this to reuse it later
- apply the throttle to both fleet 1 and fleet 2 pages
- increased the throttle time to 750 ms
> fix enter key shortcut management in fleet page for expeditions

- src/ogkush.js
partial fix that enables ogi to not be broken by v11.3.0
- production data it is only right with ALL 100% production factors
- production factors calculation still to be implemented
- items production still to be implemented
- crawler production will be wrong in some cases
> partial fix for v11.3.0 empire production data changes

- src/ogkush.js
When player's main planet is relocated, main planet is missing from player's planet list and activities cant be pushed to PTRE.
This fixes this bug.
Also setting `main` in counter-spy message sending.
> fix(activities): Fix main planet missing error when pushing activities

- src/ogkush.js
When using player search (in right panel), we want to track activities for selected player in historic. 
Every time a player is selected in historic, he is added as last element of this list `searchHistory`. This PR aims to test last element of `searchHistory` and push activities as a if it was a regular target in `sideStalk`.
> feat(activities): Track right-pinned player activities

- src/ogkush.js
- src/util/service.ptre.js
First PTRE endpoints used `HTTP_REFERER` to guess source country and universe.
As some browsers (Brave, i think) dont set `HTTP_REFERER`, some background requests to PTRE fail.
This PR aims to add thoses parameters to each PTRE requests as GET parameters.
> fix(ptre): Add country and universe to PTRE endpoints

- src/ogkush.js
**DRAFT**
Refacto PTRE call by using service for galaxy activities pushs. It was already used for conter-spy messages, not sure why it was not used for galaxy activities pushs.
Before, we need to merge:
- https://github.com/ogame-infinity/web-extension/pull/280
- https://github.com/ogame-infinity/web-extension/pull/282
Then, i will rebase PR
> refacto(ptre): Move activity push call to PTRE service

- src/ogkush.js
- initializeLFTypeName() now can be used in moons
- updateEmpireData() in Update button in settings now do a forced call
- the waiting tooltip now waits to self-close for completion of updateEmpireData()
> Fix/initializeLFTypeName() + update button in settings

- src/ctxpage/conf-options.js
- src/ogkush.js
The options _(OGInfinity.json.options)_ are extracted from the main build and declared in _./ctxpage/conf-options.js_.
The new implementation allows to get the configuration from different parts without the need to transport the OGInfinity instance.
In this implementation there are three exposed functions.
```ts
/// file: src/ctxpage/conf-options.js
/** Gets all declared options.  */
getOptions() : ProxyOptions;
/** Gets the value of an existing option */
getOption(name: string) : any | undefined;
/* Allows to set the value of a previously existing or non-existing option. */
setOption(name: string, value: any) : void;
```
In the case of `getOptions()` the proxy used prevents new options from being declared directly. If you need to add a new option it is recommended to add it directly in …
> The options are extracted from the main init

- src/ctxcontent/helpers/universe.data.js
- src/ctxcontent/services/request.ogameServerData.js
- src/ctxcontent/services/universe.expirations.js
- src/ctxcontent/services/universe.storage.js
- src/util/fetching.js
- src/util/json.js
1. A new service was added to request data from the OGame server, which contains information about the game universe.
2. *Add expiry utility for fetch requests*: A private field is introduced for the fetch utility to store the expiry timestamp, initially set to -1. This private field is populated based on the 'Expires' header if available.
3. *Adds functionality to handle JSON with advanced types: Introduces a new file containing functionality to transform advanced data types to JSON and vice versa.
4. *Adds functionality to manage universe storage: Introduces new functionality to save and retrieve data associated with a universe and a key in Chrome storage.
5. *Adds functionality to manage universe expirations*: Introduces new functions to set an expiry date for a universe key, to check …
> Feature: Universe Expiration request and universe storage with TTL

- src/global.css
- src/ogkush.js
Change design of pos16 debris to some alike regular debris one. This minimalist style makes easy to make room for the new direct expedition button feature with a slim pos16 row.
> change debris pos16 design to some alike regular debris

- src/global.css
Revert planetName max-width size to the previous one to avoid really long player names to split in two lines.
before:
after:
> use previous planetName width size in galaxy

- src/ogkush.js
When 
is enable
If you already have a chat with someone, 
This button don't work
=> patched
> fix: send message when Deactivate chat bar enable

- src/ctxpage/conf-options.js
- src/ctxpage/overview/OverviewPage.js
- src/global.css
- src/ogkush.js
A special demand from my child: to see the planet skins without anything blocking the view.
So i added a button to hide the planet data div, and another to hide the buff bar.
It work for planets and moons.
> Add prettier overview functionality with toggle buttons for details and buff bar

- src/global.css
- src/ogkush.js
- src/util/OGIData.js
- src/util/markerui.js
- src/util/stalk.js
Allow to mark a player with a color:
- All coords are marked with the chosen color
- It's possible to mark a coords as usual with another color
When the player marke is removed:
- all coords of the player color are removed
- other coords remain untouched
When navigating in the galaxy view:
- if an unmarked coord is encoutered for a marker player, this coord is automatically marked withe the player color
Need advice for cleaning data when a player id is remove (banned user, removed account, etc.)
> Add player marker functionality

- src/ogkush.js
Regarding the evolution of the construction icons, since it retrieves information from the DOM, there might be some display shortcomings when switching from a PC to a phone, or when using the commander's construction lists.
Actually, it's possible to retrieve construction information directly from the empire page. Of course, it's incomplete (it doesn't have the end date), but at least the data is as "fresh" as possible.
> Implement work in progress tech tracking for planets and moons directly from empire data

- src/ogkush.js
> fix - disable ENTER shortcut in player search textInput

- src/ogkush.js
When clicking on a building or ship icon, whose display mode is set to Visible, a redirection to the overview page is performed, instead of keeping the context of the current page
> fix: update fleet and construction icon links to use current page context
